Migrate to Swift 3 syntax
cezarywojcik/CWStatusBarNotification pull request #99
Opened 2016-10-06 07:24 UTC by dewski

I was trying to use this in a Swift 3 project with no success, luckily most of this translated 1:1 over to Swift 3 code and its idioms.

![image](https://cloud.githubusercontent.com/assets/79995/19143668/4cf2942c-8b5a-11e6-9b24-b40e5a23bc4e.png)

Feel free to pick and choose any of these changes!

/cc @cezarywojcik

2016-10-06 07:43 UTC, cezarywojcik requested changes

2016-10-06 07:43 UTC, cezarywojcik commented on CWStatusBarNotification/CWStatusBarNotification/CWStatusBarNotification.swift
> +    public func displayNotification(_ message : String,
Please keep the `withMessage` label to retain parity with obj-c api

2016-10-06 07:43 UTC, cezarywojcik commented on CWStatusBarNotification/CWStatusBarNotification/CWStatusBarNotification.swift
> +                                                         selector: #selector(CWStatusBarNotification.updateStatusBarFrame),
what's going on with indentation here?

2016-10-06 07:43 UTC, cezarywojcik commented on CWStatusBarNotification/CWStatusBarNotification/CWStatusBarNotification.swift
> +                                                                name: .UIApplicationDidChangeStatusBarFrame,
this intentation is weird too

2016-12-06 00:52 UTC, JeromeTW commented
Is this brunch work for Swift 3 and Xcode8？？
how to install it by cocoapod?
pod 'CWStatusBarNotification', :git => 'https://github.com/cezarywojcik/CWStatusBarNotification', :commit => 'f2a358dc8b7db9e6136f3a993a08b49e56cca5fc'

2021-09-22 22:08 UTC, closed without merging